### ISSUE TITLE
Distance tools AndroidManifest.xml:3: error: ERROR: missing 'android:name' for uses-permission

### ISSUE THREAD

**Issue by AlBeix** [10MINT/extensions#1]
Hi There

Really appreciate your Distance tools Extension and it works beautifully in development on my Tablet.

When I tried to load the App to Google Play for Alpha testing it fails with a message as follows.

**Upload failed**
Your APK cannot be analyzed using aapt. Error output:
Failed to run aapt dump badging:
AndroidManifest.xml:3: error: ERROR: missing 'android:name' for uses-permission

In searching for answers I received the following Email from Evan Patton

"Okay. I just grabbed your AIA and pulled it apart. It looks like the distancetools extension includes a permissions array with the empty string. That's likely the cause of the problem. You may want to reach out to the extension developer for an update.

Regards,
Evan"

Can you look into this and supply an update to fix this?

Thanks in advance.

Regards

Al Beix
Kaslo,BC
Canada

**Comment by 10MINT** [comment]
Fixed. Thanks for your research!

**Comment by AlBeix** [comment]
Thanks for the \Prompt response, Will redownload and give it a whirl.

**Comment by AlBeix** [comment]
Hi 

I have  further to the problem I am experiencing with uploading your Distance tools extension.

In a subsequent response Evan Patton wrote as follows ...
From the forum: An extension whose component_build_infos.json file contains a permissions array with a single empty string results in apps that cannot be uploaded to the Play Store. We implicitly trust the contents of the component_build_infos.json file, and don't check to see whether the permission is valid. There are two things we need to do:

 In ExternalComponentGenerator or its superclass, filter out any empty strings from all of the build info fields. This will prevent introducing the problem into new extensions.
 In Compiler, filter out any empty strings for any of the build info fields to compensate for extensions that haven't been updated/fixed.
----------------------------
Thought I would pass this along in case it offers you any additional info, the AI2 gang have logged this as issue# 1102.
