### ISSUE TITLE
Re Fix to Distance Tools

### ISSUE THREAD

**Issue by AlBeix** [10MINT/extensions#2]
Hi There

I deleted the original Distance tools, in my App, imported the new download and redid the associated code, rebuilt the APK file and when I tried to upload it to google play I get the same error. as seen below 

Upload failed
Your APK cannot be analyzed using aapt. Error output:
Failed to run aapt dump badging:
AndroidManifest.xml:3: error: ERROR: missing 'android:name' for uses-permission

Not sure if it makes any difference, but I noticed this morning that it was built for Thunkable whereas I work on the Google hosted MIT AI2.

Could that be causing this?
_

**Comment by 10MINT** [comment]
That's strange. I can't test it, but often the reupload does not work. Are you really sure the uploading process was successful?

**Comment by AlBeix** [comment]
Will try again

I will also try an upload with no extension and see it works with native code only.

**Comment by AlBeix** [comment]
Hi 

I think there must still be an  issue in Distance tools because a version without the Distance Tools extension loads successfully to the Google play store but when I try it with the extension tools included it gets rejected with the same error.

UPDATE - I also downloaded the Distance.aia file from your github repository, built the APK and tried loading that on google play which produced the same error.

**Comment by 10MINT** [comment]
I saw your post on the other topic and that was just what the MIT team can do on their side. I deleted the line of code and compiled the extension. The .aia file did not work because I did not update it. Can you do one last check since you are woking in App Inventor and check which version it says if you click the question mark? I'll see what I can do

**Comment by AlBeix** [comment]
Hi ? (What is your Name?)

I checked as requested and the Dist Tools shows as version 3

After tomorrow I will not be working on this project for three weeks, but will have Email access if you need or want to get in touch.

AL

**Comment by 10MINT** [comment]
It should work now. Sorry for the inconvenience

**Comment by AlBeix** [comment]
No Worries I Will redo the download, add the code and resubmit. Will let you know the results.

**Comment by AlBeix** [comment]
Hi ??
I believe you can now mark this as resolved since it is now loaded up on the Google play server for Alpha Testing.

I sincerely appreciate your timely efforts to work with me in resolving this.  If you would like to send me a Paypalme link I will make a donation to assist your efforts.

**Comment by 10MINT** [comment]
Donations are appreciated. [paypal.me/lennartwenke](https://www.paypal.me/lennartwenke)
Regards, Lennart Wenke
